### ISSUE TITLE
just doesn't works

### ISSUE THREAD

**Issue by alexey-sh** [Tomohiro/airplayer#55]
Users/alexey/.rvm/gems/ruby-2.4.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFTypes.rb:24: warning: constant ::Fixnum is deprecated
/Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/configuration.rb:29: warning: constant ::Fixnum is deprecated
/Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/browser.rb:24:in `browse': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd/service.rb:253:in `_resolve': DNSSD operation failed with error code: -65540 (DNSSD::BadParamError)
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd/service.rb:253:in `resolve'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/browser.rb:125:in `resolve'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/browser.rb:26:in `block (2 levels) in browse'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd/service.rb:164:in `process'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd/service.rb:66:in `browse'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd.rb:178:in `run'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/dnssd-2.0.1/lib/dnssd.rb:86:in `browse!'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/browser.rb:25:in `block in browse'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /Users/alexey/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/timeout.rb:122:in `timeout'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay/browser.rb:24:in `browse'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay.rb:34:in `browse'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplay-1.0.3/lib/airplay.rb:62:in `devices'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/device.rb:5:in `devices'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/device.rb:20:in `exist?'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/device.rb:11:in `get'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/controller.rb:6:in `initialize'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/app.rb:10:in `new'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/lib/airplayer/app.rb:10:in `play'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/gems/airplayer-1.0.1/bin/airplayer:5:in `<top (required)>'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/bin/airplayer:22:in `load'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/bin/airplayer:22:in `<main>'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/alexey/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tomohiro** [comment]
Thank you for your reporting.

**Comment by alexey-sh** [comment]
thank you too for the awesome library
